name: deploy-auth
on:
  push:
    branches:
      - main
    paths:
      - 'auth/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t kshubhamz/ticketing-auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PAASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push kshubhamz/ticketing-auth
      # an example using digital-ocean
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{  secrets.DIGITALOCEAN_ACCESSTOKEN }}
      - run: doctl kunernetes cluster kubeconfig save <DIGITALOCEAN_CLUSTERNAME>
      - run: kubectl rollout restart deployment <AUTH_DEPLOYMENT_NAME>
