name: deploy-manifest
on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # an example using digital-ocean
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{  secrets.DIGITALOCEAN_ACCESSTOKEN }}
      - run: doctl kunernetes cluster kubeconfig save <DIGITALOCEAN_CLUSTERNAME>
      - run: kubectl apply -f infra/k8s
